---
# tasks file for common

- name: Configure etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
  tags: common

- name: Disable selinux
  template:
    src: selinux.j2
    dest: /etc/sysconfig/selinux
  tags: common
  when: ansible_os_family == "EL"

- name: Update Ubuntu apt cache
  apt: update_cache=yes
  when: ansible_os_family == "Debian"
  tags: common

- name: Update all Ubuntu packages
  apt: upgrade=dist
  when: ansible_os_family == "Debian"
  tags: common

- name: reboot host
  shell: nohup bash -c "sleep 2s && reboot" &
  register: reboot
  tags: common

- name: wait for host boot
  become: false
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host }}"
    port: 22
    delay: "{{ boot_wait | default(60) }}"
    timeout: 120
    state: started
  when: reboot.changed
  tags: common
